export const MeniuConstructionItems = [
    {
        title:"Constructi",
        path:'/addConstruction',
        cName:'dropdown-link',
    },
    {
        title:"Sudura",
        path:'/addWeld',
        cName:'dropdown-link',
    },
    {
        title:"Amenajere",
        path:'/addOutSide',
        cName:'dropdown-link',
    },
    {
        title:"Cosmetice",
        path:'/addStyle',
        cName:'dropdown-link',
    }
]